import {library} from "@fortawesome/fontawesome-svg-core";
import {faCcVisa, faWaze} from "@fortawesome/free-brands-svg-icons";
import {
  faBookmark as faBookmarkOutline,
  faCalendarPlus,
  faHeart as faHeartOutline
} from "@fortawesome/free-regular-svg-icons";
import {
  faArrowLeft,
  faArrowRight,
  faBookmark,
  faCartPlus,
  faCartShopping,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faClose,
  faCoins,
  faGear,
  faHeart,
  faInfo,
  faMars,
  faMedal,
  faMinus,
  faPalette,
  faPersonWalking,
  faPlus,
  faQuestion,
  faRotateRight,
  faSearch,
  faStar,
  faTrash,
  faTruck,
  faUser,
  faVenus
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faRotateRight,
  faArrowRight,
  faArrowLeft,
  faMars,
  faVenus,
  faQuestion,
  faStar,
  faClose,
  faCartPlus,
  faHeart,
  faHeartOutline,
  faBookmark,
  faBookmarkOutline,
  faCartShopping,
  faCoins,
  faMedal,
  faWaze,
  faUser,
  faGear,
  faCalendarPlus,
  faPlus,
  faMinus,
  faTrash,
  faTruck,
  faPersonWalking,
  faCcVisa,
  faSearch,
  faInfo,
  faPalette
);
